name: yeast
instruction: "Navigate the yeast cell to the red laser dot."
target_generator: YeastGenerator
target_params:
  major_min: 20.0
  major_max: 35.0
  aspect_ratio_range: [0.6, 0.9]
  num_bumps: [3, 7]
  bump_amp: 0.06
pid_kp: 0.4
pid_ki: 0.01
pid_kd: 0.08
